"""empty message

Revision ID: ebc944841063
Revises: 79085fc92590
Create Date: 2016-09-02 17:45:44.783429

"""

# revision identifiers, used by Alembic.
revision = 'ebc944841063'
down_revision = '79085fc92590'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brewlogs', sa.Column('rating', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brewlogs', 'rating')
    ### end Alembic commands ###
